### PR TITLE
Upgrade to Go 1.19

### LINKED ISSUE #395: GH checks on the PR failing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Standalone DSPO (without ODH)

### Version

V1.5.0

### Environment

GH Actions/workflows.

### Current Behavior

The GH action checks on PRs to this repository are failing with Unit Tests and Functional Tests with the following errors:
Error: ../../../go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
make: *** [Makefile:198: /home/runner/work/data-science-pipelines-operator/data-science-pipelines-operator/bin/setup-envtest] Error 2
Error: Process completed with exit code 2.

### Expected Behavior

All the CI checks should pass.

### Steps To Reproduce

Create a new PR for this repo. 

### Workaround (if any)

_No response_

### Anything else

Following are the PRs which has the mentioned issue:

https://github.com/opendatahub-io/data-science-pipelines-operator/pull/394

https://github.com/opendatahub-io/data-science-pipelines-operator/pull/391

### PR DESCRIPTION
**Pull request by gmfrasca**
## The issue resolved by this Pull Request:
Resolves #395 

## Description of your changes:
Upgrades Golang version from 1.18 to 1.19

## Testing instructions
- First, verify `make test`, assert unit and func tests pass (as well as CI on GitHub).
- Build via `make build`
- Run via `make run`, or `go run bin/manager -config=$configfile` assuming config file exists

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-396`

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by gmfrasca** [comment]
downstream changes issue (since image change needed): https://github.com/red-hat-data-services/data-science-pipelines-operator/issues/46

**Pull request merged**
