### PR TITLE
FIX - Update metadata envoy service name in mlpipelines-ui deployment file

### PR DESCRIPTION
**Pull request by VaniHaripriya**
## The issue resolved by this Pull Request:
Resolves [RHOAIENG-5348](https://issues.redhat.com/browse/RHOAIENG-5348)

## Description of your changes:

- Updated mlpipelines-ui deployment file with the updated metadata-envoy service host . 
- Updated metadata-envoy-serviceaccount with the new service name.

## Testing instructions
Created this PR to fix the below error in kfp-ui which was caused by the changes done with this PR-https://github.com/opendatahub-io/data-science-pipelines-operator/pull/650-

Error occurred while trying to proxy request /ml_metadata.MetadataStoreService/GetContextByTypeAndName from ds-pipeline-ui-sample-dspa1.apps.rosa.hukhan.wrh7.p3.openshiftapps.com to http://ds-pipeline-metadata-envoy-sample:9090/ (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Deploy DSPO and create a DSPA instance. Create a pipeline run and make sure there are no errors in the UI and should be able to see the pipeline status.

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-653`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/653/head
git checkout -b pullrequest 819a6b93b818569cf1f75ac07db4e2af48f13ea6
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-653"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-653`

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by hbelmiro — APPROVED** [review]
/approve

Deployed and ran a pipeline successfully.

Screenshot from 2024-05-22 09-47-01

**Pull request merged**
