### PR TITLE
feat: always enable server config and make it customizable

### PR DESCRIPTION
**Pull request by HumairAK**
## Description of your changes:
We should always mount the server config, regadless of whether we have a custom cabundle or not, so that we don't end up in a situation where based on the cabundle we are using different configs, as that may result in different behaviors if somehow the default config in the dsp server image ends up diverging from the one we mount.

To prevent future issues with server config, this pr also adds the ability for users to provide a custom sever config, in case the default options are not sufficient, the user can customize their own server config in such a case, for instance changing the path in s3 where pipelines are stored.

The name for the default server config is also renamed to be consistent with the rest of the dspa's resource naming pattern "ds-pipelines-*"

## Testing instructions
1. Deploy simple dspa
2. confirm server-config is mounted, in the pipeline server pod you should see the following: 

```yaml
         volumeMounts:
            - name: server-config
              mountPath: /config/config.json
              subPath: config.json
```
3. confirm pipeline runs successfully
4. In a separate namespace, deploy another dspa but with a custom server config, for example: 
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-script
  namespace: dspa1
  labels:
    app: ds-pipeline-test
    component: data-science-pipelines
data:
  blah: |
    {
      "DBConfig": {
        "MySQLConfig": {
          "ExtraParams": {"tls":"false"},
          "GroupConcatMaxLen": "4194304"
         },
        "PostgreSQLConfig": {},
        "ConMaxLifeTime": "120s"
      },
      "DBDriverName": "mysql",
      "InitConnectionTimeout": "6m",
      "CacheEnabled": "false"
    }

```

and in dspa: 

```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: test
spec:
  apiServer:
    customServerConfigMap:
      name: custom-script
      key: blah
  dspVersion: v2
  objectStorage:

    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
  mlpipelineUI:
    image: quay.io/opendatahub/ds-pipelines-frontend:latest
```

then inspect the apiserver mounts: 

```yaml
 volumeMounts:
    - name: server-config
      mountPath: /config/config.json
      subPath: blah
```

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-605`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/605/head
git checkout -b pullrequest a3ceacb47f3fd4c0bb0d5f9acdf49b904394a39b
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-605"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-605`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-605`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-605`

**Review by amadhusu — APPROVED** [review]
Worked as suggested with the default server config and customized one as well. Pipelines ran successfully as well.

<details>
<summary>default server config</summary>

Screenshot from 2024-03-15 20-09-13

Screenshot from 2024-03-15 20-10-24

</details>

<details>
<summary> custom server config </summary>

Screenshot from 2024-03-15 20-19-22

Screenshot from 2024-03-15 20-20-21

</details>

**Pull request merged**
