### PR TITLE
Updating DSP repo references in GH actions

### PR DESCRIPTION
**Pull request by DharmitD**
## Description of your changes:
Updating DSP repo references in GH actions to point to the `opendatahub-io/data-science-pipelines-tekton` repository.

## Checklist
- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by gregsheremeta** [comment]
@HumairAK @DharmitD are we good to close this?

**Comment by DharmitD** [comment]
> @HumairAK @DharmitD are we good to close this?

I still see some references to the old repo on both main and dspv2 branches. For instance :https://github.com/opendatahub-io/data-science-pipelines-operator/blob/dspv2/.github/scripts/release_prep/create_branches.sh

We should probably rebase this PR and then merge it?

**Comment by HumairAK** [comment]
yes

**Pull request closed without merging**
