### PR TITLE
Added new section for Deployment and testing guidelines for Developers

### LINKED ISSUE #159: Write Contributing/Testing process documentation
Write a document that specifies the standard testing/deployment procedure **for developers**.  The spirit behind this issue is that there are multiple competing ways to deploy and/or test out a PR changeset (publish a container image, `make deploy`, apply YAMLs directly, etc), and it is unclear for reviewers exactly which procedure to follow.

### PR DESCRIPTION
**Pull request by VaniHaripriya**
## The issue resolved by this Pull Request:
Resolves #159

## Description of your changes:
Added new section with Deployment and testing process for developers.

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

@VaniHaripriya could you please create an issue to log the unit and function test CI failures?

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-391`

**Comment by DharmitD** [comment]
@VaniHaripriya Could you please check your rebase steps again? Looks like the rebase added a bunch of separate commits to the PR.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-391`

**Comment by VaniHaripriya** [comment]
Created a new PR - https://github.com/opendatahub-io/data-science-pipelines-operator/pull/399

**Pull request closed without merging**
