### PR TITLE
fix: update oauth-proxy-image and MLMD Envoy images

### PR DESCRIPTION
**Pull request by jgarciao**
Setting the same image that rhoai dashboard is currently using

## The issue resolved by this Pull Request:
Resolves [RHOAIENG-14652](https://issues.redhat.com/browse/RHOAIENG-14652) and [RHOAIENG-11441](https://issues.redhat.com/browse/RHOAIENG-11441)

## Description of your changes:
Updates the oauth-proxy image to use version [v4.14.0-202408260910.p0.ga4a2f27.assembly.stream.el8](https://catalog.redhat.com/software/containers/openshift4/ose-oauth-proxy/5cdb2133bed8bd5717d5ae64?image=66cefc14401df6ff4664ec43&container-tabs=gti), in order to fix a compatibility issue with OpenShift 4.16+ FIPS clusters

Note: this PR is setting the same image that the dashboard team used to the same error recently in [RHOAIENG-10450](https://issues.redhat.com/browse/RHOAIENG-10450), but it is possible that it will have to be updated again once the initiative to standardize these images is developed (more info at [RHOAIENG-11357](https://issues.redhat.com/browse/RHOAIENG-11357))

Updates also the MLMD Envoy image. New version is [2.5.5-6](https://catalog.redhat.com/software/containers/openshift-service-mesh/proxyv2-rhel8/5d2cda455a134672890f640a?image=66f66f4e5f86ba811464415f)

## Testing instructions
Follow the testing instructions at [RHOAIENG-14652](https://issues.redhat.com/browse/RHOAIENG-14652). Contact @jgarciao if you need a FIPS cluster

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
   - I could not build dspo locally. I tested it manually modifying the image in the dspa Deployment

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-725`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/725/head
git checkout -b pullrequest e12b1a6d78b634ec184802c7347e3c72306771d6
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-725"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Comment by gregsheremeta** [comment]
the SHAs make this hard -- are there version numbers that those map to? It would be nice to know what version we were on and what version we're upgrading to.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-725`

**Comment by jgarciao** [comment]
I've updated also the MLMD Envoy image, as @HumairAK requested in slack.

@gregsheremeta , I've added the image versions in the descriptioni. Both have grade still A

**Pull request merged**
