### PR TITLE
Dspv2 merge - Sprint 9 Check-in Merge 2

### LINKED ISSUE #471: Pull in changes from main into v2 feature branch - Sprint 9

### PR DESCRIPTION
**Pull request by gmfrasca**
## The issue resolved by this Pull Request:
Resolves #471 

## Description of your changes:
Pull in changes from `main` branch, Nov 15 - Dec 19

## Testing instructions
Run standard sanity checks

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-521`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/521/head
git checkout -b pullrequest a1fc85c56bbd667462a139195717cc59c6b05368
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-521"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-521`

**Review by rimolive — COMMENTED** [review]
/lgtm

Deployment went fine, and the iris-pipeline example ran successfuly

**Pull request merged**
