### PR TITLE
Improve documentation for tLSClientConfig

### PR DESCRIPTION
**Pull request by diegolovison**
## Description of your changes:
GoDoc-style comment for your tLSClientConfig function

## Testing instructions
NA

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Review by DharmitD — APPROVED** [review]
/Approve

**Comment by DharmitD** [comment]
Put a hold on merging due to CI failure: https://github.com/opendatahub-io/data-science-pipelines-operator/actions/runs/10835954834/job/30068595888?pr=700

but the failure isn't related to this PRs updates.

/unhold
/Approve

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-700`

**Review by DharmitD — APPROVED** [review]
/Approve

**Pull request merged**
