### PR TITLE
RHOAIENG-5243 - Added overlays for deploying dspo and argo separately

### PR DESCRIPTION
**Pull request by amadhusu**
## The issue resolved by this Pull Request:
Resolves [RHOAIENG-5243](https://issues.redhat.com/browse/RHOAIENG-5243)

## Description of your changes:
Added overlays for deploying dspo and argo separately

## Testing instructions
Normal Sanity checks to see if everything is working as it should.

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-626`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/626/head
git checkout -b pullrequest eae9ef2b80f37c91a33301c953a0c1b7746fbbab
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-626"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by HumairAK** [comment]
@VaishnaviHire  or @zdtsw  

wdyt about splitting up the overlays in this way, so odh operator can introduce an option to deploy with or without argo by pointing at one, or both nested overlays

**Comment by zdtsw** [comment]
food for thought:  what i can see the difference for "odh" and "rhoai" is only the namespace "opendatahub" vs "redhat-ods-applications"?
then why not to only keep one but set a configmap to get the proper namespace?
say in params.env you can have a 
`namespace=opendatahub` when deploy to rhoai by RHOAI operator, we will replace this to `namespace=redhat-ods-applicatons`
all you need is to add this into configMapGenerator, looking for data.namespace, e.g 
```
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: dsp-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
```

**Comment by zdtsw** [comment]
> @VaishnaviHire or @zdtsw
> 
> wdyt about splitting up the overlays in this way, so odh operator can introduce an option to deploy with or without argo by pointing at one, or both nested overlays

yeah, this is one of the things i was considering weeks ago.
odh operator only need to check if "some condition is matched, i.e Argo CRD in cluster" we can deploy "argo" or fall back to the "tekton" one.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-626`

**Comment by HumairAK** [comment]
> food for thought: what i can see the difference for "odh" and "rhoai" is only the namespace "opendatahub" vs "redhat-ods-applications"?
then why not to only keep one but set a configmap to get the proper namespace?
say in params.env you can have a


@zdtsw , the intended purpose of this design is to allow us to easily patch rhoai/odh specific changes as needed, without affecting the other platform

Furthermore, we are currently reconsidering in slack whether we want to make it possible for the user to deploy their own argo at all (i.e. we always try to deploy argo), regardless I think we should still go through this change even if we have a no-op from rhoai/odh operator side, to offer flexibility in the future should we change our minds. Also it can be good to have for dev testing. 

/lgtm
/appear

**Pull request merged**
