### PR TITLE
Added routes permissions to pipeline runner

### PR DESCRIPTION
**Pull request by Ygnas**
## The issue resolved by this Pull Request:
Resolves https://issues.redhat.com/browse/RHOAIENG-7346

## Description of your changes:

Adds route.openshift.io->routes->get, list permissions
## Testing instructions

No testing should be necessary here, but these permissions fixed the codeflare-sdk running using pipelines

For DW verification:
```
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/654/head
git checkout -b pullrequest c025c7243bb58166df4471d5b416ddf83cedfd98
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-654"
```

Configure the pipeline server and create default `LocalQueue` in the opendatahub.

Upload this https://issues.redhat.com/secure/attachment/13193837/pipeline.yaml and run the pipeline.

Should not get credential errors from here https://issues.redhat.com/browse/RHOAIENG-7346, and pipeline should finish successfully.

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-654`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/654/head
git checkout -b pullrequest 2505bd9d32ffc52ad101d3125849779251d6fafc
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-654"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-654`

**Review by Bobbins228 — COMMENTED** [review]
/lgtm
Tested this with CodeFlare SDK all good!

**Pull request merged**
