### PR TITLE
add newlines between certs

### PR DESCRIPTION
**Pull request by HumairAK**
## The issue resolved by this Pull Request:
Resolves https://issues.redhat.com/browse/RHOAIENG-11297

## Description of your changes:
If odh-trusted-ca-bundle has now newline, it concatenates the ca bundle with service-ca without any newline separate, an easy fix is to ensure there is always at least one new line between each ca bundle merge. 

## Testing instructions

Deploy podtopodtls in a self-signed environment with odh-trusted bundle with no newline at the end of file, run a pipeline, if it succeeds, it works.

Note that I have also adjusted the func tests to ignore trailing spaces, because it's incredibly buggy and non-intuitive to make work correctly, testing these portions should be saved for unit testing.

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-685`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-685`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-685`

**Comment by diegolovison** [comment]
Due to the we are combining certificates from multiple sources I would like to ask for a new test (ref 1).

- openshift-service-ca.crt
- odh-trsuted-ca-bundle
- dspa -> spec.apiServer
- dsci

are combined into `dsp-trusted-ca-dspa`

Each source is a multi-line string YAML attribute, the multi-line string can be represented by `|`, `|-`,  `|+`, `>`, `>-`, `>+`

Here is an example:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-line-test
data:
  ex1: |-
    Line one.
    Line two.
  ex2: |
    Line one.
    Line two.
  ex3: |+
    Line one.
    Line two.
  ex4: >-
    Line one.
    Line two.
  ex5: >
    Line one.
    Line two.
  ex6: >+
    Line one.
    Line two.    
```

`ex4`, `ex5`, and `ex6` can be disregarded because it will result in an invalid certificate. They will remove the new line resulting in the content in a single line.

**ref 1**
We should focus on `ex1`, `ex2`, and `ex3`. Having a test providing the certificate attribute with `|`, `|-`,  `|+` and asserting the result.

**Comment by HumairAK** [comment]
@diegolovison these tests cases are covered with the PR, except for DSCI, which requires ODH to test, which the current infra does not support, adding odh testing warrants a ticket of its own.

**Pull request merged**
