### PR TITLE
chore: deploy mariadb nwp with mariadb

### PR DESCRIPTION
**Pull request by HumairAK**
## The issue resolved by this Pull Request:
Resolves https://issues.redhat.com/browse/RHOAIENG-5314

## Description of your changes:
ensures the NWP is deployed along with mariadb, otherwise the DSPO will attempt to verify connection to mariadb without the nwp.

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-647`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/647/head
git checkout -b pullrequest 7ac94f5c0f01684f197543fedcdc99ede3f96533
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-647"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by VaniHaripriya — COMMENTED** [review]
/lgtm Just nit pick change- Please update networkpolicy  name instead of newtorkpolicy

**Comment by HumairAK** [comment]
@VaniHaripriya the naming is consistent with the other files in the directory

**Comment by HumairAK** [comment]
nvm I noticed the typo, updated

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-647`

**Pull request merged**
