### PR TITLE
Upgrade Argo images to v3.4.17

### PR DESCRIPTION
**Pull request by rimolive**
## The issue resolved by this Pull Request:
Resolves #<issue_number>

## Checklist
- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-718`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/718/head
git checkout -b pullrequest 62d605572dcd01d76ff34df140aedcb177cad8f4
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-718"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by gregsheremeta** [comment]
lgtm

is this part of a ticket?

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
