### PR TITLE
Parameterized HealthCheck Timeouts

### PR DESCRIPTION
**Pull request by hbelmiro**
## The issue resolved by this Pull Request:
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/328

## Description of your changes:
Parameterized `DBConnectionTimeout` and `ObjStoreConnectionTimeout`.
`MaxConcurrentReconciles` was already parameterized.

## Testing instructions

Set the variables `DB_CONNECTION_TIMEOUT` and `OBJ_STORE_CONNECTION_TIMEOUT`, run DSPO, create a DSPA, and ensure the DSPA deploys correctly.

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-433`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/433/head
git checkout -b pullrequest d8289bcddd83160cbbd3f00a2b227bac8a7d0f3f
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-433"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by gmfrasca — COMMENTED** [review]
I hate to propose something drastically different, but I feel like these should be configurable fields in the DSPA CRD (ie `.database.healthchecktimeout`) rather than a CLI parameter

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-433`

**Review by gmfrasca — COMMENTED** [review]
needs rebased but otherwise /lgtm

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-433`

**Review by DharmitD — APPROVED** [review]
/Approve

**Review by gmfrasca — APPROVED** [review]

**Pull request merged**
