### PR TITLE
Remove kind/resource type mentions from metadata.name in resources

### PR DESCRIPTION
**Pull request by amadhusu**
## The issue resolved by this Pull Request:
Resolves [RHOAIENG-1680](https://issues.redhat.com/browse/RHOAIENG-1680)

## Description of your changes:
This PR removes kind/resource type mentions from metadata.name in resources

## Testing instructions
Just normal Sanity checks

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-557`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/557/head
git checkout -b pullrequest 11d6114a7fa26b92f480e3d4536b90e25cbcf1da
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-557"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by gregsheremeta — COMMENTED** [review]
Aren't there RoleBindings that would need to be changed as well? (edit: or in this case, ClusterRoleBindings...)

**Comment by amadhusu** [comment]
> Aren't there RoleBindings that would need to be changed as well? (edit: or in this case, ClusterRoleBindings...)

I couldn't find any ClusterRoleBindings in this case. Do you have a reference point if any?

**Comment by gregsheremeta** [comment]
Nope, I'm not very familiar with them.

@gmfrasca do you know if there are ClusterRoleBindings somewhere that would also need to be changed?

**Comment by DharmitD** [comment]
> Nope, I'm not very familiar with them.
> 
> @gmfrasca do you know if there are ClusterRoleBindings somewhere that would also need to be changed?

If you look at the commit history you can find CRBs in this commit:
https://github.com/opendatahub-io/data-science-pipelines-operator/commit/2fec33481ad87da7de6aee6a5ba56125e31d75ec
And not in the next one: https://github.com/opendatahub-io/data-science-pipelines-operator/commit/027e8abfc98c41acfc1f284a2c3a1caa396baa44

Not sure if they were moved to deleted.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-557`

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Pull request merged**
