### PR TITLE
DSPv2

### LINKED ISSUE #534: DSPv2 feature branch into main

### PR DESCRIPTION
**Pull request by gmfrasca**
## The issue resolved by this Pull Request:
Resolves #534 

## Description of your changes:
Merge in dspv2 feature branch

## Testing instructions
Full Testing suite required.  Deploy DSPO, ensure sanity. Deploy v1 and v2 DSPAs

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-539`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/539/head
git checkout -b pullrequest cd786d97ebdbca735a76a11891df824d4a448419
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-539"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by hbelmiro** [comment]
There's a [DSPA](https://github.com/hbelmiro/data-science-pipelines-operator/tree/issue-498/config/samples/v2/custom-configs) failing with `Cannot get MLMD objects from Metadata store`.

### How to reproduce

Check out this branch:

```bash
gh pr checkout 539
```

On a fresh cluster, deploy Argo:

```bash
oc new-project argo
make argodeploy
```

Create the `opendatahub` namespace:

```bash
oc new-project opendatahub
```

Deploy DSPO from the branch:

```bash
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-539"
```

Create the `kubeflow` namespace:

```bash
oc new-project kubeflow
```

Checkout https://github.com/hbelmiro/data-science-pipelines-operator/tree/issue-498:

```bash
gh pr checkout 541
```

Deploy the DSPA to the `kubeflow` namespace:

```bash
kustomize build config/samples/v2/custom-configs | oc -n kubeflow create -f -
```

Get the route for the DSPA:

```bash
oc get route ds-pipeline-ui-sample -n kubeflow
```

Open the URL in the browser and start a new pipeline run. In the pipeline run view, you'll see the error message after a few seconds.

Screenshot from 2024-01-12 10-38-15

**Comment by gmfrasca** [comment]
> There's a [DSPA](https://github.com/hbelmiro/data-science-pipelines-operator/tree/issue-498/config/samples/v2/custom-configs) failing with `Cannot get MLMD objects from Metadata store`.

I retested this on a couple clusters, one of which was freshly provisioned, and wasn't able to reproduce the problem.  I did notice that the error message was shown on the run when first kicked off, but it very quickly resolved on its own, and i believe had to do with creating the run so soon after DSPA creation.

**Review by hbelmiro — APPROVED** [review]

**Comment by gregsheremeta** [comment]
/hold

let's make sure this merged while everyone is awake / around

**Comment by gregsheremeta** [comment]
/approve

:shipit:

**Review by amadhusu — APPROVED** [review]

**Pull request merged**
