### PR TITLE
Add Custom CA Bundle Injection into DSP via DSPA

### PR DESCRIPTION
**Pull request by HumairAK**
## The issue resolved by this Pull Request:
Resolves https://github.com/opendatahub-io/data-science-pipelines-operator/issues/362

## Description of your changes:
Add CA Injection capabilities to api server pod and pipeline s3 copy steps.

## Testing instructions

Deploy DSPO

```
# git clone and checkout the PR branch
make deploy IMG=quay.io/opendatahub/data-science-pipelines-operator:pr-440
```

Deploy a Minio in a self-signed external OCP cluster (preferablly different from the dsp host cluster) 
```
oc new-project minio
oc -n minio apply -f https://gist.githubusercontent.com/HumairAK/f1358278ab70dde2ee074d1a35f8f058/raw/f234ba638f408c3aff8ed836858d0d1e332f43be/minio.yaml

# Retrieve the route
$MINIO_ROUTE=$(oc get routes -n minio minio-secure --template={{.spec.host}})
```

On DSP host cluster, deploy a dspa, first without the cabundle: 

<details> 

<summary>dspa.yaml</summary>

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: s3secret
  namespace: dspa
stringData:
  customaccessKey: accesskey
  customsecretKey: secretkey
type: Opaque
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
  namespace: dspa
spec:
  apiServer:
    enableSamplePipeline: false
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: $MINIO_ROUTE  # <------------- add the route retrieved earlier !
      s3CredentialsSecret:
        accessKey: customaccessKey
        secretKey: customsecretKey
        secretName: s3secret
      scheme: https
  mlpipelineUI:
    image: 'quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui'
```

</details>

Check DSPO logs, you should see an error mentioning x509 and instructions on adding a cabundle. 
From the minio self-signed ocp cluster get the ca bundle from `minio` namespace: 

```
oc -n minio get configmap kube-root-ca.crt -o yaml | yq '.data."ca.crt"'  > ca-bundle.crt
```

Put this value in a configmap: 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-minio-ca-bundle
data:
  ca-bundle.crt: |
    # contents of ca-bundle.crt
```

Deploy this in the DSPA namespace. Then update the dspa to be: 

<details>

<summary>dspa.yaml</summary>

```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
spec:
  apiServer:
    enableSamplePipeline: false
    cABundle:               # We add the configmap details here, mouse over this field in ocp to see the field descriptions
      configMapKey: ca-bundle.crt
      configMapName: custom-minio-ca-bundle
  database:
    disableHealthCheck: true
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: $MINIO_ROUTE  # <------------- add the route retrieved earlier !
      s3CredentialsSecret:
        accessKey: customaccessKey
        secretKey: customsecretKey
        secretName: s3secret
      scheme: https
  mlpipelineUI:
    image: 'quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui'

```
</details>

Once deployed you will see the DSPA get deployed successfully, run an iris pipeline, make sure the artifact passing is successful (does s3 data get storec successfully? does pipeline run to completion) ? 

Also confirm no regression, (if it's an http minio, does that still work?) etc. 

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-440`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/440/head
git checkout -b pullrequest 2c3f9d3515cef6c8548b05a1fb65b4c54c831baf
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-440"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-440`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-440`

**Review by rimolive — COMMENTED** [review]
/lgtm
/approve

**Comment by HumairAK** [comment]
@gregsheremeta

**Comment by gregsheremeta** [comment]
> Check DSPO logs, you should see an error mentioning x509 and instructions on adding a cabundle.

I didn't see this. The first thing that happens is that the health check fails.
```
2023-11-03T18:24:34Z INFO Performing Object Storage Health Check {"namespace": "dspa1", "dspa_name": "dspa1"}
2023-11-03T18:24:34Z INFO Could not connect to object storage endpoint: https://minio-api-minioself.apps.rosa.greg-1002.xb4x.p3.openshiftapps.com {"namespace": "dspa1", "dspa_name": "dspa1"}
2023-11-03T18:24:34Z INFO Object Storage Health Check Failed {"namespace": "dspa1", "dspa_name": "dspa1"}
2023-11-03T18:24:34Z INFO Updating CR status {"namespace": "dspa1", "dspa_name": "dspa1"}
```

Searching the logs for the word "cabundle" turns up empty.

Need to add something like [this](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/440/files#diff-6caebac9ae3dd8fc2e64acb065a396ada98de75be84e5d8f22872bdd33a5b881R132) to the health check flow too?

**Comment by gregsheremeta** [comment]
> The advantage would be that I only have to add custom trusted CAs and self-signed certs in PEM format once at central cluster Proxy config in a secret in namespace openshift-config, which is much more streamlined and less distributed.

Long term, we are pursuing a global cluster-level approach. Whether that uses the Proxy or not is TBD.

A future global cluster-level approach does not obviate the need for component-level control as well.

**Comment by shalberd** [comment]
some comments from Graig and me on the [topic of future improvements and possible architecture direction](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/440#issuecomment-1799074925) when it comes to self-signed certificate and private PKI CA trust.

**Pull request merged**
