### PR TITLE
Rename package_upload.sh to package_download.sh

### PR DESCRIPTION
**Pull request by diegolovison**
## Description of your changes:
It is a rename of files to match exactly what they are doing

## Testing instructions
NA

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Review by DharmitD — APPROVED** [review]
/Approve

**Pull request merged**
