### PR TITLE
WIP: Update Manifests for Argo v3.4.16

### PR DESCRIPTION
**Pull request by gmfrasca**
## The issue resolved by this Pull Request:
Resolves #TODO

## Description of your changes:
Updates argo manifests for use with argo v3.4.16

Restructures the `config/argo` directory to match argoproj/argo-workflows manifests for easier maintenance.  (The names and contents remain generally the same)

## Testing instructions
Run `make deploy`, wait for DSPO to become available, then deploy a simple DSPA.  Verify workflows still run

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-606`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-606`

**Comment by jgarciao** [comment]
@gmfrasca I think this PR can be closed now, as argo 3.4.17 is in main now

**Comment by gregsheremeta** [comment]
agreed

/close

**Pull request closed without merging**
