### PR TITLE
Up dspo memory to handle more users.

### PR DESCRIPTION
**Pull request by HumairAK**
## Description
Based on our performance testing, dspo with 4Gi memory and current cpu allotment can handle upwards of ~2k OCP users submitting DSPA's.

## Merge criteria:
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
:+1:

**Review by DharmitD — APPROVED** [review]
/Approve

**Pull request merged**
