### PR TITLE
Remove ViewerCRD deployment

### PR DESCRIPTION
**Pull request by rimolive**
## Description
Remove viewerCRD from Operator code. This is part of the work to make DSPA simpler, deploying only the components that will be part of the Data Science Pipelines release.

## How Has This Been Tested?
* `make run`
* Deploy Any DSPA CR
* Check if the messages to deploy viewerCRD are gone

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

Skimmed through changes and checked e2e logs.

**Comment by HumairAK** [comment]
@rimolive I still see lots of mentions of viewer crd in the codebase: 

* readme component section: https://github.com/opendatahub-io/data-science-pipelines/pull/82
* https://github.com/rimolive/data-science-pipelines-operator/blob/rmartine/config/internal/common/policy.yaml.tmpl#L48 
* https://github.com/rimolive/data-science-pipelines-operator/blob/rmartine/controllers/testdata/declarative/case_0/expected/not_created/viewer-crd_deployment.yaml
* https://github.com/rimolive/data-science-pipelines-operator/blob/rmartine/controllers/testdata/declarative/case_1/expected/not_created/viewer-crd_deployment.yaml


Also is this crd still needed? 
https://github.com/rimolive/data-science-pipelines-operator/blob/rmartine/config/crd/bases/viewers.yaml

**Pull request merged**
