### PR TITLE
Updated description in datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml

### PR DESCRIPTION
**Pull request by hbelmiro**
## Description of your changes:

This PR fixes a description that is automatically generated. This probably was caused by a missing file in a previous commit.

### How to reproduce

1. Checkout the main branch.
2. Run `make functest`
3. Run `git status` and you'll see this update.

### How to test
1. Checkout this branch
2. Run `make functest`
3. Run `git status`. No changes must be shown.

## Checklist
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-625`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/625/head
git checkout -b pullrequest 4330cd76b8a337f67caf0dcea11c60d1cefda227
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-625"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by amadhusu — APPROVED** [review]
Nice, yep we should check for these cases where `make generate` was missed by a previous change to the file `api/v1alpha1/dspipeline_types.go`

**Review by DharmitD — APPROVED** [review]
/Approve

**Pull request merged**
