### PR TITLE
Release v2.5.0

### PR DESCRIPTION
**Pull request by dsp-developers**
This is an automated PR to prep Data Science Pipelines Operator for release.
```yaml

odh_org: opendatahub-io
release_branch: v2.5.x
target_version_tag: v2.5.0
previous_release_tag: v2.4.0
```

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-690`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/690/head
git checkout -b pullrequest 092b2543ac8fa3d8a985358d57bd3fcd5ed7885b
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-690"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by gregsheremeta** [comment]
I'm not as familiar with these as I'd like to be. Do you need someone to review this, or is it auto-approve since it's automated?

**Comment by HumairAK** [comment]
@gregsheremeta at this stage, it's just `main` contents that have been built, with `params` updated with digests, so everything should already have been confirmed, at this stage we can just do more sanity checks if we need to. 

/lgtm
/approve

**Comment by dsp-developers** [comment]
Release created successfully:

https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.5.0

https://github.com/opendatahub-io/data-science-pipelines/releases/tag/v2.5.0

**Pull request merged**
