### PR TITLE
V1.5.x

### PR DESCRIPTION
**Pull request by HumairAK**
Cherry-pick: 
* https://github.com/opendatahub-io/data-science-pipelines-operator/commit/31ed583475c083275ff83819c071896be0ac95e6
* https://github.com/opendatahub-io/data-science-pipelines-operator/commit/a2b531cc771b2bd417411945c2545d4ebb963882
* https://github.com/opendatahub-io/data-science-pipelines-operator/commit/b15a878b3a54e5b0293c01d08bfdc6790e6a0965
* https://github.com/opendatahub-io/data-science-pipelines-operator/commit/5c786ad80b217e5f73a88afe2a0928dc24a010f5

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-524`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/524/head
git checkout -b pullrequest e874fa4bf88a39ac3e232715b24a4e8a03eb24b8
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-524"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-524`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-524`

**Comment by HumairAK** [comment]
Ignoring pre-comit ci failure as it's not relevant for this patch.

**Pull request merged**
