### PR TITLE
Rename Custom Resource name to  DataSciencePipelinesApplication. 

### PR DESCRIPTION
**Pull request by HumairAK**
## Description
Since DSPipeline can be easily confused with a single pipeline run, we
have instead decided to go with a more meaningful/descriptive CR name.

## How Has This Been Tested?
Locally and on OCP OSD with: quay.io/hukhan/data-science-pipelines-operator:v0.0.8
Run unit tests on this pr by cloning the branch and following instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#run-tests). 

Deploy on dev cluster with ocp pipelines (logged in as cluster admin): 

```
oc new-project data-science-pipelines-operator
make podman-build podman-push IMG=$YOUR_CONTAINER_REPO
make deploy IMG=$YOUR_CONTAINER_REPO
```

Deploy a sample cr with the updated resource kind: 

```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: sample
  namespace: data-science-project
spec: {}
```

## Merge criteria:
Requires: https://github.com/opendatahub-io/data-science-pipelines-operator/pull/27

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by DharmitD — APPROVED** [review]
/approve

Deployed changes on a local cluster, resources came up as expected.

**Pull request merged**
