### PR TITLE
Upgrade envoy proxy image and configuration

### PR DESCRIPTION
**Pull request by rimolive**
## The issue resolved by this Pull Request:
Resolves [RHOAIENG-4259](https://issues.redhat.com/browse/RHOAIENG-4259)

## Description of your changes:
MLMD envoy proxy image uses a very outdated version. This proposal is to upgrade to 1.26 and upgrade proxy configuration.

## Testing instructions
* Build a new operator image
* Deploy DSPO and a DSPA
* Run the example pipeline

## Checklist
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dsp-developers** [comment]
A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-596`
An OCP cluster where you are logged in as cluster admin is required.

To use this image run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines-operator.git
cd data-science-pipelines-operator/
git fetch origin pull/596/head
git checkout -b pullrequest dd7c4cc9e099b2850ad903cfbe1501256f896c0c
oc new-project opendatahub
make deploy IMG="quay.io/opendatahub/data-science-pipelines-operator:pr-596"
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-596`

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A new image has been built to help with testing out this PR: `quay.io/opendatahub/data-science-pipelines-operator:pr-596`

**Review by amadhusu — APPROVED** [review]
Verified everything works fine according to Testing instructions.

**Pull request merged**
